using System;

namespace NeonRunner.Core
{
    /// <summary>
    /// Input action types for the tick-based input system.
    /// Each action is an atomic, instantaneous command.
    /// </summary>
    public enum InputAction : byte
    {
        None = 0,
        LaneLeft = 1,
        LaneRight = 2,
        Jump = 3,
        Slide = 4,
    }

    /// <summary>
    /// A single recorded input at a specific tick.
    /// </summary>
    [Serializable]
    public struct TickInput : IEquatable<TickInput>
    {
        public int Tick;
        public InputAction Action;

        public TickInput(int tick, InputAction action)
        {
            Tick = tick;
            Action = action;
        }

        public bool Equals(TickInput other) => Tick == other.Tick && Action == other.Action;
        public override bool Equals(object obj) => obj is TickInput t && Equals(t);
        public override int GetHashCode() => Tick.GetHashCode() ^ ((int)Action << 24);
        public override string ToString() => $"[T{Tick}:{Action}]";
    }

    /// <summary>
    /// Obstacle types that can be generated.
    /// </summary>
    public enum ObstacleType : byte
    {
        // Standard obstacles
        LowBarrier = 0,     // Must jump
        HighBarrier = 1,    // Must slide
        FullBlock = 2,      // Must lane-change

        // Skill challenges
        SkillGate = 10,     // Tight gap — high reward
        RiskTunnel = 11,    // Dense obstacle zone — multiplier

        // Bonus
        BonusPath = 20,     // Optional harder route
        ScorePickup = 21,   // Collect for points
    }

    /// <summary>
    /// Lane positions.
    /// </summary>
    public enum Lane : byte
    {
        Left = 0,
        Center = 1,
        Right = 2,
    }

    /// <summary>
    /// Runner vertical state.
    /// </summary>
    public enum VerticalState : byte
    {
        Running = 0,
        Jumping = 1,
        Sliding = 2,
    }

    /// <summary>
    /// Game phase for difficulty progression.
    /// </summary>
    public enum GamePhase : byte
    {
        Onboarding = 0,   // 0–30s: easy, tutorial-like
        SkillZone = 1,    // 30–90s: moderate challenge
        Escalation = 2,   // 90s+: ramping difficulty
        Endgame = 3,      // 180s+: extreme
    }

    /// <summary>
    /// Modifier flags that can be applied to a challenge.
    /// </summary>
    [Flags]
    public enum GameModifiers : ushort
    {
        None = 0,
        SpeedX12 = 1 << 0,       // 1.2x speed
        SpeedX15 = 1 << 1,       // 1.5x speed
        SpeedX20 = 1 << 2,       // 2.0x speed
        LowVisibility = 1 << 3,  // Fog/darkness
        SlipperyControls = 1 << 4,
        DoubleScoreZones = 1 << 5,
        HardcoreMode = 1 << 6,   // No forgiveness
        OneLife = 1 << 7,
        TwoLives = 1 << 8,
    }

    /// <summary>
    /// Obstacle data generated by the spawner.
    /// Pure data — no Unity references.
    /// </summary>
    public struct ObstacleData
    {
        public int Id;
        public ObstacleType Type;
        public Lane Lane;
        public FixedVec3 Position;
        public FixedVec3 HalfExtents;
        public bool IsActive;
        public int SpawnTick;

        /// <summary>
        /// Score bonus for near-miss with this obstacle.
        /// Higher for harder obstacles.
        /// </summary>
        public int NearMissBonus;

        public AABB GetAABB() => new AABB(Position, HalfExtents);
    }

    /// <summary>
    /// Complete runner state at any given tick.
    /// Pure data struct — can be serialized, compared, hashed.
    /// </summary>
    public struct RunnerState
    {
        public Lane CurrentLane;
        public Lane TargetLane;
        public VerticalState Vertical;
        public FixedVec3 Position;
        public Fixed Speed;
        public Fixed JumpProgress;     // 0 to 1 during jump
        public Fixed SlideProgress;    // 0 to 1 during slide
        public Fixed LaneSwitchProgress; // 0 to 1 during lane transition
        public bool IsAlive;
        public int Lives;
        public int CurrentTick;
        public Fixed TotalDistance;
    }

    /// <summary>
    /// Complete simulation snapshot.
    /// </summary>
    public struct SimulationSnapshot
    {
        public RunnerState Runner;
        public int Score;
        public int ComboCount;
        public Fixed ComboMultiplier;
        public Fixed RiskMultiplier;
        public GamePhase Phase;
        public Fixed TimeElapsed;   // In fixed-point seconds
        public int ObstaclesPassed;
        public int NearMisses;
        public int PerfectDodges;
        public int MaxCombo;
        public int SkillGatesPassed;
    }

    /// <summary>
    /// Configuration for a game session.
    /// </summary>
    public struct GameConfig
    {
        public long Seed;
        public GameModifiers Modifiers;
        public Fixed TimeLimitSeconds;  // Zero = endless
        public int StartingLives;       // Default 1

        public static GameConfig Default => new GameConfig
        {
            Seed = 0,
            Modifiers = GameModifiers.None,
            TimeLimitSeconds = Fixed.Zero,
            StartingLives = 1,
        };
    }

    /// <summary>
    /// Near-miss detection result.
    /// </summary>
    public struct NearMissResult
    {
        public bool Occurred;
        public Fixed ClosestDistance;
        public int ObstacleId;
        public bool IsPerfectDodge;
    }
}
